steps:

- id: 'Configure Maven'
  name: maven:3-jdk-8
  entrypoint: mvn
  args: ['--version']
  
  
- id: 'Build Maven Package'
  name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
   
- id: 'Build Docker Image'
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io//backend:latest', '--build-arg=JAR_FILE=target/build-artifact', '.']

- id: 'Push Docker Image to GCR'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io//backend:latest']

